package com.crystal.mystia_izakaya.dataGen;

import com.crystal.mystia_izakaya.registry.ItemRegistry;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.ItemTagsProvider;
import net.minecraft.tags.ItemTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import org.hiedacamellia.mystiasizakaya.registries.MIItem;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

import static com.crystal.mystia_izakaya.MystiaIzakaya.resourceLocation;

public class ModTagItem extends ItemTagsProvider {
    public static final TagKey<Item> FOOD_INGREDIENTS = TagKey.create(Registries.ITEM, resourceLocation("food_ingredients"));

    public static final TagKey<Item> SPECIALTY = TagKey.create(Registries.ITEM, resourceLocation("specialty"));
    public static final TagKey<Item> AURA_BURSTING = TagKey.create(Registries.ITEM, resourceLocation("aura_bursting"));
    public static final TagKey<Item> CULTURE_HERITAGE = TagKey.create(Registries.ITEM, resourceLocation("culture_heritage"));
    public static final TagKey<Item> STRENGTH_BOOSTING = TagKey.create(Registries.ITEM, resourceLocation("strength_boosting"));
    public static final TagKey<Item> JAPANESE = TagKey.create(Registries.ITEM, resourceLocation("japanese"));
    public static final TagKey<Item> CHINESE = TagKey.create(Registries.ITEM, resourceLocation("chinese"));
    public static final TagKey<Item> ECONOMICAL = TagKey.create(Registries.ITEM, resourceLocation("economical"));
    public static final TagKey<Item> MEAT = TagKey.create(Registries.ITEM, resourceLocation("meat"));
    public static final TagKey<Item> HOMECOOKING = TagKey.create(Registries.ITEM, resourceLocation("homecooking"));
    public static final TagKey<Item> SEA_DELICACY = TagKey.create(Registries.ITEM, resourceLocation("sea_delicacy"));
    public static final TagKey<Item> POISON = TagKey.create(Registries.ITEM, resourceLocation("poison"));
    public static final TagKey<Item> GRILLED = TagKey.create(Registries.ITEM, resourceLocation("grilled"));
    public static final TagKey<Item> DREAMY = TagKey.create(Registries.ITEM, resourceLocation("dreamy"));
    public static final TagKey<Item> SOUP = TagKey.create(Registries.ITEM, resourceLocation("soup"));
    public static final TagKey<Item> FRUITY = TagKey.create(Registries.ITEM, resourceLocation("fruity"));
    public static final TagKey<Item> PREMIUM = TagKey.create(Registries.ITEM, resourceLocation("premium"));
    public static final TagKey<Item> FRESH = TagKey.create(Registries.ITEM, resourceLocation("fresh"));
    public static final TagKey<Item> SWEET = TagKey.create(Registries.ITEM, resourceLocation("sweet"));
    public static final TagKey<Item> SIGNATURE = TagKey.create(Registries.ITEM, resourceLocation("signature"));
    public static final TagKey<Item> LEGENDARY = TagKey.create(Registries.ITEM, resourceLocation("legendary"));
    public static final TagKey<Item> GREASY = TagKey.create(Registries.ITEM, resourceLocation("greasy"));
    public static final TagKey<Item> REFRESHING = TagKey.create(Registries.ITEM, resourceLocation("refreshing"));
    public static final TagKey<Item> RAW = TagKey.create(Registries.ITEM, resourceLocation("raw"));
    public static final TagKey<Item> EMPTY = TagKey.create(Registries.ITEM, resourceLocation("empty"));
    public static final TagKey<Item> VEGETARIAN = TagKey.create(Registries.ITEM, resourceLocation("vegetarian"));
    public static final TagKey<Item> WESTERN = TagKey.create(Registries.ITEM, resourceLocation("western"));
    public static final TagKey<Item> SPICY = TagKey.create(Registries.ITEM, resourceLocation("spicy"));
    public static final TagKey<Item> GOOD_ALCOHOL = TagKey.create(Registries.ITEM, resourceLocation("good_alcohol"));
    public static final TagKey<Item> MILD = TagKey.create(Registries.ITEM, resourceLocation("mild"));
    public static final TagKey<Item> WONDERFUL = TagKey.create(Registries.ITEM, resourceLocation("wonderful"));
    public static final TagKey<Item> SMALL_PORTION = TagKey.create(Registries.ITEM, resourceLocation("small_portion"));
    public static final TagKey<Item> MOUNTAIN_DELICACY = TagKey.create(Registries.ITEM, resourceLocation("mountain_delicacy"));
    public static final TagKey<Item> PECULIAR = TagKey.create(Registries.ITEM, resourceLocation("peculiar"));
    public static final TagKey<Item> SALTY = TagKey.create(Registries.ITEM, resourceLocation("salty"));
    public static final TagKey<Item> SOUR = TagKey.create(Registries.ITEM, resourceLocation("sour"));
    public static final TagKey<Item> FILLING = TagKey.create(Registries.ITEM, resourceLocation("filling"));
    public static final TagKey<Item> LARGE_PORTION = TagKey.create(Registries.ITEM, resourceLocation("large_portion"));
    public static final TagKey<Item> AQUATIC = TagKey.create(Registries.ITEM, resourceLocation("aquatic"));
    public static final TagKey<Item> PHOTOGENIC = TagKey.create(Registries.ITEM, resourceLocation("photogenic"));
    public static final TagKey<Item> EXPENSIVE = TagKey.create(Registries.ITEM, resourceLocation("expensive"));
    public static final TagKey<Item> HOT = TagKey.create(Registries.ITEM, resourceLocation("hot"));
    public static final TagKey<Item> FUNGUS = TagKey.create(Registries.ITEM, resourceLocation("fungus"));

    public ModTagItem(PackOutput pOutput, CompletableFuture<HolderLookup.Provider> pLookupProvider, CompletableFuture<TagLookup<Block>> pBlockTags, String modId, @Nullable ExistingFileHelper existingFileHelper) {
        super(pOutput, pLookupProvider, pBlockTags, modId, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.@NotNull Provider pProvider) {
        this.tag(ItemTags.FISHING_ENCHANTABLE).add(ItemRegistry.MystiaFishingRod.value());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Crab.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Grill.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Trout.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Lamprey.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Salmon.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Tuna.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Premium_Tuna.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Pufferfish.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Shrimp.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Octopus.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Sea_Urchin.get());

        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Pork.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Beef.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Venison.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Boar_Meat.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Iberico_Pork.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Wagyo_Beef.get());

        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Tofu.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Potato.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Onion.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Pumpkin.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Radish.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Seaweed.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Mushroom.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Truffle.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Bamboo_Shoot.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Cucumber.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Chestnut.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Red_Toon.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Tomato.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Broceoli.get());

        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Egg.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Ginko_Nut.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Cicada_Slough.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Dew.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Flour.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Sticky_Rice.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Ice_Cube.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Grapes.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Cream.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Lemon.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Lotus_Seed.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Pine_Nut.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Red_Bean.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Cocoa_Bean.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Snow_Fungus.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Peach.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Honey.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Udunmbara.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Butter.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Bamboo.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Lunar_Herb.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Chili.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Black_Salt.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Bingdi_Lotus.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Cheese.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Sweet_Potato.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Plum.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Flower.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Creeping_Fig.get());

        this.tag(FRESH).add(ItemRegistry.Crab.get());
        this.tag(FRESH).add(ItemRegistry.Sea_Urchin.get());
        this.tag(FRESH).add(ItemRegistry.Octopus.get());
        this.tag(FRESH).add(ItemRegistry.Shrimp.get());
        this.tag(FRESH).add(ItemRegistry.Pufferfish.get());
        this.tag(FRESH).add(ItemRegistry.Premium_Tuna.get());
        this.tag(FRESH).add(ItemRegistry.Tuna.get());
        this.tag(FRESH).add(ItemRegistry.Salmon.get());
        this.tag(FRESH).add(ItemRegistry.Lamprey.get());
        this.tag(FRESH).add(ItemRegistry.Trout.get());
        this.tag(FRESH).add(ItemRegistry.Onion.get());
        this.tag(FRESH).add(ItemRegistry.Seaweed.get());
        this.tag(FRESH).add(ItemRegistry.Mushroom.get());
        this.tag(FRESH).add(ItemRegistry.Truffle.get());
        this.tag(FRESH).add(ItemRegistry.Cheese.get());
        this.tag(LEGENDARY).add(ItemRegistry.Sea_Urchin.get());
        this.tag(LEGENDARY).add(ItemRegistry.Premium_Tuna.get());
        this.tag(LEGENDARY).add(ItemRegistry.Iberico_Pork.get());
        this.tag(LEGENDARY).add(ItemRegistry.Wagyo_Beef.get());
        this.tag(LEGENDARY).add(ItemRegistry.Truffle.get());
        this.tag(LEGENDARY).add(ItemRegistry.Udunmbara.get());
        this.tag(LEGENDARY).add(ItemRegistry.Bingdi_Lotus.get());
        this.tag(SPICY).add(ItemRegistry.Chili.get());
        this.tag(MOUNTAIN_DELICACY).add(ItemRegistry.Iberico_Pork.get());
        this.tag(MOUNTAIN_DELICACY).add(ItemRegistry.Truffle.get());
        this.tag(RAW).add(ItemRegistry.Egg.get());
        this.tag(DREAMY).add(ItemRegistry.Udunmbara.get());
        this.tag(DREAMY).add(ItemRegistry.Lunar_Herb.get());
        this.tag(DREAMY).add(ItemRegistry.Bingdi_Lotus.get());
        this.tag(DREAMY).add(ItemRegistry.Flower.get());
        this.tag(PREMIUM).add(ItemRegistry.Crab.get());
        this.tag(PREMIUM).add(ItemRegistry.Sea_Urchin.get());
        this.tag(PREMIUM).add(ItemRegistry.Premium_Tuna.get());
        this.tag(PREMIUM).add(ItemRegistry.Tuna.get());
        this.tag(PREMIUM).add(ItemRegistry.Salmon.get());
        this.tag(PREMIUM).add(ItemRegistry.Wagyo_Beef.get());
        this.tag(PREMIUM).add(ItemRegistry.Truffle.get());
        this.tag(PREMIUM).add(ItemRegistry.Pine_Nut.get());
        this.tag(PREMIUM).add(ItemRegistry.Udunmbara.get());
        this.tag(PREMIUM).add(ItemRegistry.Bingdi_Lotus.get());
        this.tag(PREMIUM).add(ItemRegistry.Cheese.get());
        this.tag(MEAT).add(ItemRegistry.Pork.get());
        this.tag(MEAT).add(ItemRegistry.Beef.get());
        this.tag(MEAT).add(ItemRegistry.Venison.get());
        this.tag(MEAT).add(ItemRegistry.Boar_Meat.get());
        this.tag(MEAT).add(ItemRegistry.Iberico_Pork.get());
        this.tag(MEAT).add(ItemRegistry.Wagyo_Beef.get());
        this.tag(MILD).add(ItemRegistry.Tofu.get());
        this.tag(MILD).add(ItemRegistry.Bamboo_Shoot.get());
        this.tag(MILD).add(ItemRegistry.Cucumber.get());
        this.tag(MILD).add(ItemRegistry.Dew.get());
        this.tag(MILD).add(ItemRegistry.Lotus_Seed.get());
        this.tag(MILD).add(ItemRegistry.Pine_Nut.get());
        this.tag(MILD).add(ItemRegistry.Snow_Fungus.get());
        this.tag(MILD).add(ItemRegistry.Lunar_Herb.get());
        this.tag(MILD).add(ItemRegistry.Bingdi_Lotus.get());
        this.tag(WESTERN).add(ItemRegistry.Cream.get());
        this.tag(GREASY).add(ItemRegistry.Butter.get());
        this.tag(FUNGUS).add(ItemRegistry.Mushroom.get());
        this.tag(FUNGUS).add(ItemRegistry.Truffle.get());
        this.tag(FUNGUS).add(ItemRegistry.Snow_Fungus.get());
        this.tag(AQUATIC).add(ItemRegistry.Crab.get());
        this.tag(AQUATIC).add(ItemRegistry.Sea_Urchin.get());
        this.tag(AQUATIC).add(ItemRegistry.Octopus.get());
        this.tag(AQUATIC).add(ItemRegistry.Shrimp.get());
        this.tag(AQUATIC).add(ItemRegistry.Pufferfish.get());
        this.tag(AQUATIC).add(ItemRegistry.Premium_Tuna.get());
        this.tag(AQUATIC).add(ItemRegistry.Tuna.get());
        this.tag(AQUATIC).add(ItemRegistry.Salmon.get());
        this.tag(AQUATIC).add(ItemRegistry.Lamprey.get());
        this.tag(AQUATIC).add(ItemRegistry.Trout.get());
        this.tag(SWEET).add(ItemRegistry.Cream.get());
        this.tag(SWEET).add(ItemRegistry.Cocoa_Bean.get());
        this.tag(SWEET).add(ItemRegistry.Peach.get());
        this.tag(SWEET).add(ItemRegistry.Honey.get());
        this.tag(FILLING).add(ItemRegistry.Pumpkin.get());
        this.tag(FILLING).add(ItemRegistry.Flour.get());
        this.tag(FILLING).add(ItemRegistry.Sweet_Potato.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Tofu.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Potato.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Cucumber.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Chestnut.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Broceoli.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Cream.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Red_Bean.get());
        this.tag(PHOTOGENIC).add(ItemRegistry.Ginko_Nut.get());
        this.tag(PHOTOGENIC).add(ItemRegistry.Bamboo.get());
        this.tag(PHOTOGENIC).add(ItemRegistry.Flower.get());
        this.tag(REFRESHING).add(ItemRegistry.Ice_Cube.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Tofu.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Potato.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Onion.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Pumpkin.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Radish.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Seaweed.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Mushroom.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Truffle.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Bamboo_Shoot.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Cucumber.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Chestnut.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Red_Toon.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Tomato.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Broceoli.get());
        this.tag(SMALL_PORTION).add(ItemRegistry.Plum.get());
        this.tag(SEA_DELICACY).add(ItemRegistry.Sea_Urchin.get());
        this.tag(SEA_DELICACY).add(ItemRegistry.Octopus.get());
        this.tag(SEA_DELICACY).add(ItemRegistry.Pufferfish.get());
        this.tag(SEA_DELICACY).add(ItemRegistry.Premium_Tuna.get());
        this.tag(PECULIAR).add(ItemRegistry.Cicada_Slough.get());
        this.tag(GOOD_ALCOHOL).add(ItemRegistry.Radish.get());
        this.tag(FRUITY).add(ItemRegistry.Grapes.get());
        this.tag(FRUITY).add(ItemRegistry.Lemon.get());
        this.tag(FRUITY).add(ItemRegistry.Peach.get());
        this.tag(SIGNATURE).add(ItemRegistry.Lamprey.get());
        this.tag(SIGNATURE).add(ItemRegistry.Lotus_Seed.get());
        this.tag(SIGNATURE).add(ItemRegistry.Pine_Nut.get());
        this.tag(WONDERFUL).add(ItemRegistry.Cocoa_Bean.get());
        this.tag(WONDERFUL).add(ItemRegistry.Udunmbara.get());
        this.tag(WONDERFUL).add(ItemRegistry.Lunar_Herb.get());
        this.tag(POISON).add(ItemRegistry.Red_Toon.get());
        this.tag(CULTURE_HERITAGE).add(ItemRegistry.Lotus_Seed.get());
        this.tag(CULTURE_HERITAGE).add(ItemRegistry.Lunar_Herb.get());
        this.tag(CULTURE_HERITAGE).add(ItemRegistry.Bingdi_Lotus.get());
        this.tag(SALTY).add(ItemRegistry.Black_Salt.get());
        this.tag(SALTY).add(ItemRegistry.Cheese.get());
        this.tag(SALTY).add(ItemRegistry.Plum.get());
        this.tag(SOUR).add(ItemRegistry.Lemon.get());

        compat();
    }

    private void compat() {
        this.tag(FOOD_INGREDIENTS).add(MIItem.PANG_XIE.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.HAI_DAN.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.ZHANG_YU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.XIA.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.HE_TUN.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.JI_SHANG_JIN_QIANG_YU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.JIN_QIANG_YU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.SAN_WEN_YU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.BA_MU_MAN.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.ZUN_YU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.ZHU_ROU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.NIU_ROU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.LU_ROU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.YE_ZHU_ROU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.HEI_MAO_ZHU_ROU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.HE_NIU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.DOU_FU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.TU_DOU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.YANG_CONG.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.NAN_GUA.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.LUO_BU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.HAI_TAI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.MO_GU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.SONG_LU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.ZHU_SUN.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.HUANG_GUA.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.BAN_LI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.CHUN_CHUN.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.XI_HONG_SHI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.XI_LAN_HUA.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.JI_DAN.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.BAI_GUO.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.CHAN_SHUI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.LU_SHUI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.MIAN_FEN.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.NUO_MI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.BING_KUAI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.PU_TAO.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.NAI_YOU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.NING_MENG.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.LIAN_ZI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.SONG_ZI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.HONG_DOU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.KE_KE_DOU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.YIN_ER.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.TAO_ZI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.FENG_MI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.HUAN_TAN_HUA.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.HUANG_YOU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.ZHU_ZI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.YUE_GUANG_CAO.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.LA_JIAO.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.HEI_YAN.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.BING_DI_LIAN.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.ZHI_SHI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.DI_GUA.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.MEI_ZI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.XIAN_HUA.get());

        this.tag(FRESH).add(MIItem.PANG_XIE.get());
        this.tag(FRESH).add(MIItem.HAI_DAN.get());
        this.tag(FRESH).add(MIItem.ZHANG_YU.get());
        this.tag(FRESH).add(MIItem.XIA.get());
        this.tag(FRESH).add(MIItem.HE_TUN.get());
        this.tag(FRESH).add(MIItem.JI_SHANG_JIN_QIANG_YU.get());
        this.tag(FRESH).add(MIItem.JIN_QIANG_YU.get());
        this.tag(FRESH).add(MIItem.SAN_WEN_YU.get());
        this.tag(FRESH).add(MIItem.BA_MU_MAN.get());
        this.tag(FRESH).add(MIItem.ZUN_YU.get());
        this.tag(FRESH).add(MIItem.YANG_CONG.get());
        this.tag(FRESH).add(MIItem.HAI_TAI.get());
        this.tag(FRESH).add(MIItem.MO_GU.get());
        this.tag(FRESH).add(MIItem.SONG_LU.get());
        this.tag(FRESH).add(MIItem.ZHI_SHI.get());
        this.tag(LEGENDARY).add(MIItem.HAI_DAN.get());
        this.tag(LEGENDARY).add(MIItem.JI_SHANG_JIN_QIANG_YU.get());
        this.tag(LEGENDARY).add(MIItem.HEI_MAO_ZHU_ROU.get());
        this.tag(LEGENDARY).add(MIItem.HE_NIU.get());
        this.tag(LEGENDARY).add(MIItem.SONG_LU.get());
        this.tag(LEGENDARY).add(MIItem.HUAN_TAN_HUA.get());
        this.tag(LEGENDARY).add(MIItem.BING_DI_LIAN.get());
        this.tag(SPICY).add(MIItem.LA_JIAO.get());
        this.tag(MOUNTAIN_DELICACY).add(MIItem.HEI_MAO_ZHU_ROU.get());
        this.tag(MOUNTAIN_DELICACY).add(MIItem.SONG_LU.get());
        this.tag(RAW).add(MIItem.JI_DAN.get());
        this.tag(DREAMY).add(MIItem.HUAN_TAN_HUA.get());
        this.tag(DREAMY).add(MIItem.YUE_GUANG_CAO.get());
        this.tag(DREAMY).add(MIItem.BING_DI_LIAN.get());
        this.tag(DREAMY).add(MIItem.XIAN_HUA.get());
        this.tag(PREMIUM).add(MIItem.PANG_XIE.get());
        this.tag(PREMIUM).add(MIItem.HAI_DAN.get());
        this.tag(PREMIUM).add(MIItem.JI_SHANG_JIN_QIANG_YU.get());
        this.tag(PREMIUM).add(MIItem.JIN_QIANG_YU.get());
        this.tag(PREMIUM).add(MIItem.SAN_WEN_YU.get());
        this.tag(PREMIUM).add(MIItem.HE_NIU.get());
        this.tag(PREMIUM).add(MIItem.SONG_LU.get());
        this.tag(PREMIUM).add(MIItem.SONG_ZI.get());
        this.tag(PREMIUM).add(MIItem.HUAN_TAN_HUA.get());
        this.tag(PREMIUM).add(MIItem.BING_DI_LIAN.get());
        this.tag(PREMIUM).add(MIItem.ZHI_SHI.get());
        this.tag(MEAT).add(MIItem.ZHU_ROU.get());
        this.tag(MEAT).add(MIItem.NIU_ROU.get());
        this.tag(MEAT).add(MIItem.LU_ROU.get());
        this.tag(MEAT).add(MIItem.YE_ZHU_ROU.get());
        this.tag(MEAT).add(MIItem.HEI_MAO_ZHU_ROU.get());
        this.tag(MEAT).add(MIItem.HE_NIU.get());
        this.tag(MILD).add(MIItem.DOU_FU.get());
        this.tag(MILD).add(MIItem.ZHU_SUN.get());
        this.tag(MILD).add(MIItem.HUANG_GUA.get());
        this.tag(MILD).add(MIItem.LU_SHUI.get());
        this.tag(MILD).add(MIItem.LIAN_ZI.get());
        this.tag(MILD).add(MIItem.SONG_ZI.get());
        this.tag(MILD).add(MIItem.YIN_ER.get());
        this.tag(MILD).add(MIItem.YUE_GUANG_CAO.get());
        this.tag(MILD).add(MIItem.BING_DI_LIAN.get());
        this.tag(WESTERN).add(MIItem.NAI_YOU.get());
        this.tag(GREASY).add(MIItem.HUANG_YOU.get());
        this.tag(FUNGUS).add(MIItem.MO_GU.get());
        this.tag(FUNGUS).add(MIItem.SONG_LU.get());
        this.tag(FUNGUS).add(MIItem.YIN_ER.get());
        this.tag(AQUATIC).add(MIItem.PANG_XIE.get());
        this.tag(AQUATIC).add(MIItem.HAI_DAN.get());
        this.tag(AQUATIC).add(MIItem.ZHANG_YU.get());
        this.tag(AQUATIC).add(MIItem.XIA.get());
        this.tag(AQUATIC).add(MIItem.HE_TUN.get());
        this.tag(AQUATIC).add(MIItem.JI_SHANG_JIN_QIANG_YU.get());
        this.tag(AQUATIC).add(MIItem.JIN_QIANG_YU.get());
        this.tag(AQUATIC).add(MIItem.SAN_WEN_YU.get());
        this.tag(AQUATIC).add(MIItem.BA_MU_MAN.get());
        this.tag(AQUATIC).add(MIItem.ZUN_YU.get());
        this.tag(SWEET).add(MIItem.NAI_YOU.get());
        this.tag(SWEET).add(MIItem.KE_KE_DOU.get());
        this.tag(SWEET).add(MIItem.TAO_ZI.get());
        this.tag(SWEET).add(MIItem.FENG_MI.get());
        this.tag(FILLING).add(MIItem.NAN_GUA.get());
        this.tag(FILLING).add(MIItem.MIAN_FEN.get());
        this.tag(FILLING).add(MIItem.DI_GUA.get());
        this.tag(HOMECOOKING).add(MIItem.DOU_FU.get());
        this.tag(HOMECOOKING).add(MIItem.TU_DOU.get());
        this.tag(HOMECOOKING).add(MIItem.HUANG_GUA.get());
        this.tag(HOMECOOKING).add(MIItem.BAN_LI.get());
        this.tag(HOMECOOKING).add(MIItem.XI_LAN_HUA.get());
        this.tag(HOMECOOKING).add(MIItem.NAI_YOU.get());
        this.tag(HOMECOOKING).add(MIItem.HONG_DOU.get());
        this.tag(PHOTOGENIC).add(MIItem.BAI_GUO.get());
        this.tag(PHOTOGENIC).add(MIItem.ZHU_ZI.get());
        this.tag(PHOTOGENIC).add(MIItem.XIAN_HUA.get());
        this.tag(REFRESHING).add(MIItem.BING_KUAI.get());
        this.tag(VEGETARIAN).add(MIItem.DOU_FU.get());
        this.tag(VEGETARIAN).add(MIItem.TU_DOU.get());
        this.tag(VEGETARIAN).add(MIItem.YANG_CONG.get());
        this.tag(VEGETARIAN).add(MIItem.NAN_GUA.get());
        this.tag(VEGETARIAN).add(MIItem.LUO_BU.get());
        this.tag(VEGETARIAN).add(MIItem.HAI_TAI.get());
        this.tag(VEGETARIAN).add(MIItem.MO_GU.get());
        this.tag(VEGETARIAN).add(MIItem.SONG_LU.get());
        this.tag(VEGETARIAN).add(MIItem.ZHU_SUN.get());
        this.tag(VEGETARIAN).add(MIItem.HUANG_GUA.get());
        this.tag(VEGETARIAN).add(MIItem.BAN_LI.get());
        this.tag(VEGETARIAN).add(MIItem.CHUN_CHUN.get());
        this.tag(VEGETARIAN).add(MIItem.XI_HONG_SHI.get());
        this.tag(VEGETARIAN).add(MIItem.XI_LAN_HUA.get());
        this.tag(SMALL_PORTION).add(MIItem.MEI_ZI.get());
        this.tag(SEA_DELICACY).add(MIItem.HAI_DAN.get());
        this.tag(SEA_DELICACY).add(MIItem.ZHANG_YU.get());
        this.tag(SEA_DELICACY).add(MIItem.HE_TUN.get());
        this.tag(SEA_DELICACY).add(MIItem.JI_SHANG_JIN_QIANG_YU.get());
        this.tag(PECULIAR).add(MIItem.CHAN_SHUI.get());
        this.tag(GOOD_ALCOHOL).add(MIItem.LUO_BU.get());
        this.tag(FRUITY).add(MIItem.PU_TAO.get());
        this.tag(FRUITY).add(MIItem.NING_MENG.get());
        this.tag(FRUITY).add(MIItem.TAO_ZI.get());
        this.tag(SIGNATURE).add(MIItem.BA_MU_MAN.get());
        this.tag(SIGNATURE).add(MIItem.LIAN_ZI.get());
        this.tag(SIGNATURE).add(MIItem.SONG_ZI.get());
        this.tag(WONDERFUL).add(MIItem.KE_KE_DOU.get());
        this.tag(WONDERFUL).add(MIItem.HUAN_TAN_HUA.get());
        this.tag(WONDERFUL).add(MIItem.YUE_GUANG_CAO.get());
        this.tag(POISON).add(MIItem.CHUN_CHUN.get());
        this.tag(CULTURE_HERITAGE).add(MIItem.LIAN_ZI.get());
        this.tag(CULTURE_HERITAGE).add(MIItem.YUE_GUANG_CAO.get());
        this.tag(CULTURE_HERITAGE).add(MIItem.BING_DI_LIAN.get());
        this.tag(SALTY).add(MIItem.HEI_YAN.get());
        this.tag(SALTY).add(MIItem.ZHI_SHI.get());
        this.tag(SALTY).add(MIItem.MEI_ZI.get());
        this.tag(SOUR).add(MIItem.NING_MENG.get());
    }
}
