package com.crystal.mystia_izakaya.dataGen;

import com.crystal.mystia_izakaya.registry.ItemRegistry;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.ItemTagsProvider;
import net.minecraft.tags.ItemTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

import static com.crystal.mystia_izakaya.MystiaIzakaya.resourceLocation;

public class ModTagItem extends ItemTagsProvider {
    public static final TagKey<Item> FOOD_INGREDIENTS = TagKey.create(Registries.ITEM, resourceLocation("food_ingredients"));

    public static final TagKey<Item> SPECIALTY = TagKey.create(Registries.ITEM, resourceLocation("specialty"));
    public static final TagKey<Item> AURA_BURSTING = TagKey.create(Registries.ITEM, resourceLocation("aura_bursting"));
    public static final TagKey<Item> CULTURE_HERITAGE = TagKey.create(Registries.ITEM, resourceLocation("culture_heritage"));
    public static final TagKey<Item> STRENGTH_BOOSTING = TagKey.create(Registries.ITEM, resourceLocation("strength_boosting"));
    public static final TagKey<Item> JAPANESE = TagKey.create(Registries.ITEM, resourceLocation("japanese"));
    public static final TagKey<Item> CHINESE = TagKey.create(Registries.ITEM, resourceLocation("chinese"));
    public static final TagKey<Item> ECONOMICAL = TagKey.create(Registries.ITEM, resourceLocation("economical"));
    public static final TagKey<Item> MEAT = TagKey.create(Registries.ITEM, resourceLocation("meat"));
    public static final TagKey<Item> HOMECOOKING = TagKey.create(Registries.ITEM, resourceLocation("homecooking"));
    public static final TagKey<Item> SEA_DELICACY = TagKey.create(Registries.ITEM, resourceLocation("sea_delicacy"));
    public static final TagKey<Item> POISON = TagKey.create(Registries.ITEM, resourceLocation("poison"));
    public static final TagKey<Item> GRILLED = TagKey.create(Registries.ITEM, resourceLocation("grilled"));
    public static final TagKey<Item> DREAMY = TagKey.create(Registries.ITEM, resourceLocation("dreamy"));
    public static final TagKey<Item> SOUP = TagKey.create(Registries.ITEM, resourceLocation("soup"));
    public static final TagKey<Item> FRUITY = TagKey.create(Registries.ITEM, resourceLocation("fruity"));
    public static final TagKey<Item> PREMIUM = TagKey.create(Registries.ITEM, resourceLocation("premium"));
    public static final TagKey<Item> FRESH = TagKey.create(Registries.ITEM, resourceLocation("fresh"));
    public static final TagKey<Item> SWEET = TagKey.create(Registries.ITEM, resourceLocation("sweet"));
    public static final TagKey<Item> SIGNATURE = TagKey.create(Registries.ITEM, resourceLocation("signature"));
    public static final TagKey<Item> LEGENDARY = TagKey.create(Registries.ITEM, resourceLocation("legendary"));
    public static final TagKey<Item> GREASY = TagKey.create(Registries.ITEM, resourceLocation("greasy"));
    public static final TagKey<Item> REFRESHING = TagKey.create(Registries.ITEM, resourceLocation("refreshing"));
    public static final TagKey<Item> RAW = TagKey.create(Registries.ITEM, resourceLocation("raw"));
    public static final TagKey<Item> EMPTY = TagKey.create(Registries.ITEM, resourceLocation("empty"));
    public static final TagKey<Item> VEGETARIAN = TagKey.create(Registries.ITEM, resourceLocation("vegetarian"));
    public static final TagKey<Item> WESTERN = TagKey.create(Registries.ITEM, resourceLocation("western"));
    public static final TagKey<Item> SPICY = TagKey.create(Registries.ITEM, resourceLocation("spicy"));
    public static final TagKey<Item> GOOD_ALCOHOL = TagKey.create(Registries.ITEM, resourceLocation("good_alcohol"));
    public static final TagKey<Item> MILD = TagKey.create(Registries.ITEM, resourceLocation("mild"));
    public static final TagKey<Item> WONDERFUL = TagKey.create(Registries.ITEM, resourceLocation("wonderful"));
    public static final TagKey<Item> SMALL_PORTION = TagKey.create(Registries.ITEM, resourceLocation("small_portion"));
    public static final TagKey<Item> MOUNTAIN_DELICACY = TagKey.create(Registries.ITEM, resourceLocation("mountain_delicacy"));
    public static final TagKey<Item> PECULIAR = TagKey.create(Registries.ITEM, resourceLocation("peculiar"));
    public static final TagKey<Item> SALTY = TagKey.create(Registries.ITEM, resourceLocation("salty"));
    public static final TagKey<Item> SOUR = TagKey.create(Registries.ITEM, resourceLocation("sour"));
    public static final TagKey<Item> FILLING = TagKey.create(Registries.ITEM, resourceLocation("filling"));
    public static final TagKey<Item> LARGE_PORTION = TagKey.create(Registries.ITEM, resourceLocation("large_portion"));
    public static final TagKey<Item> AQUATIC = TagKey.create(Registries.ITEM, resourceLocation("aquatic"));
    public static final TagKey<Item> PHOTOGENIC = TagKey.create(Registries.ITEM, resourceLocation("photogenic"));
    public static final TagKey<Item> EXPENSIVE = TagKey.create(Registries.ITEM, resourceLocation("expensive"));
    public static final TagKey<Item> HOT = TagKey.create(Registries.ITEM, resourceLocation("hot"));
    public static final TagKey<Item> FUNGUS = TagKey.create(Registries.ITEM, resourceLocation("fungus"));

    public ModTagItem(PackOutput pOutput, CompletableFuture<HolderLookup.Provider> pLookupProvider, CompletableFuture<TagLookup<Block>> pBlockTags, String modId, @Nullable ExistingFileHelper existingFileHelper) {
        super(pOutput, pLookupProvider, pBlockTags, modId, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.@NotNull Provider pProvider) {
        this.tag(ItemTags.FISHING_ENCHANTABLE).add(ItemRegistry.MystiaFishingRod.value());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Crab.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Grill.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Trout.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Lamprey.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Salmon.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Tuna.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Premium_Tuna.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Pufferfish.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Shrimp.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Octopus.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Sea_Urchin.get());

        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Pork.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Beef.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Venison.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Boar_Meat.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Iberico_Pork.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Wagyo_Beef.get());

        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Tofu.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Potato.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Onion.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Pumpkin.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Radish.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Seaweed.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Mushroom.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Truffle.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Bamboo_Shoot.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Cucumber.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Chestnut.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Red_Toon.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Tomato.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Broceoli.get());

        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Egg.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Ginko_Nut.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Cicada_Slough.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Dew.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Flour.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Sticky_Rice.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Ice_Cube.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Grapes.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Cream.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Lemon.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Lotus_Seed.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Pine_Nut.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Red_Bean.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Cocoa_Bean.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Snow_Fungus.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Peach.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Honey.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Udunmbara.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Butter.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Bamboo.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Lunar_Herb.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Chili.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Black_Salt.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Bingdi_Lotus.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Cheese.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Sweet_Potato.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Plum.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Flower.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Creeping_Fig.get());

        this.tag(FRESH).add(ItemRegistry.Crab.get());
        this.tag(FRESH).add(ItemRegistry.Sea_Urchin.get());
        this.tag(FRESH).add(ItemRegistry.Octopus.get());
        this.tag(FRESH).add(ItemRegistry.Shrimp.get());
        this.tag(FRESH).add(ItemRegistry.Pufferfish.get());
        this.tag(FRESH).add(ItemRegistry.Premium_Tuna.get());
        this.tag(FRESH).add(ItemRegistry.Tuna.get());
        this.tag(FRESH).add(ItemRegistry.Salmon.get());
        this.tag(FRESH).add(ItemRegistry.Lamprey.get());
        this.tag(FRESH).add(ItemRegistry.Trout.get());
        this.tag(FRESH).add(ItemRegistry.Onion.get());
        this.tag(FRESH).add(ItemRegistry.Seaweed.get());
        this.tag(FRESH).add(ItemRegistry.Mushroom.get());
        this.tag(FRESH).add(ItemRegistry.Truffle.get());
        this.tag(FRESH).add(ItemRegistry.Cheese.get());
        this.tag(LEGENDARY).add(ItemRegistry.Sea_Urchin.get());
        this.tag(LEGENDARY).add(ItemRegistry.Premium_Tuna.get());
        this.tag(LEGENDARY).add(ItemRegistry.Iberico_Pork.get());
        this.tag(LEGENDARY).add(ItemRegistry.Wagyo_Beef.get());
        this.tag(LEGENDARY).add(ItemRegistry.Truffle.get());
        this.tag(LEGENDARY).add(ItemRegistry.Udunmbara.get());
        this.tag(LEGENDARY).add(ItemRegistry.Bingdi_Lotus.get());
        this.tag(SPICY).add(ItemRegistry.Chili.get());
        this.tag(MOUNTAIN_DELICACY).add(ItemRegistry.Iberico_Pork.get());
        this.tag(MOUNTAIN_DELICACY).add(ItemRegistry.Truffle.get());
        this.tag(RAW).add(ItemRegistry.Egg.get());
        this.tag(DREAMY).add(ItemRegistry.Udunmbara.get());
        this.tag(DREAMY).add(ItemRegistry.Lunar_Herb.get());
        this.tag(DREAMY).add(ItemRegistry.Bingdi_Lotus.get());
        this.tag(DREAMY).add(ItemRegistry.Flower.get());
        this.tag(PREMIUM).add(ItemRegistry.Crab.get());
        this.tag(PREMIUM).add(ItemRegistry.Sea_Urchin.get());
        this.tag(PREMIUM).add(ItemRegistry.Premium_Tuna.get());
        this.tag(PREMIUM).add(ItemRegistry.Tuna.get());
        this.tag(PREMIUM).add(ItemRegistry.Salmon.get());
        this.tag(PREMIUM).add(ItemRegistry.Wagyo_Beef.get());
        this.tag(PREMIUM).add(ItemRegistry.Truffle.get());
        this.tag(PREMIUM).add(ItemRegistry.Pine_Nut.get());
        this.tag(PREMIUM).add(ItemRegistry.Udunmbara.get());
        this.tag(PREMIUM).add(ItemRegistry.Bingdi_Lotus.get());
        this.tag(PREMIUM).add(ItemRegistry.Cheese.get());
        this.tag(MEAT).add(ItemRegistry.Pork.get());
        this.tag(MEAT).add(ItemRegistry.Beef.get());
        this.tag(MEAT).add(ItemRegistry.Venison.get());
        this.tag(MEAT).add(ItemRegistry.Boar_Meat.get());
        this.tag(MEAT).add(ItemRegistry.Iberico_Pork.get());
        this.tag(MEAT).add(ItemRegistry.Wagyo_Beef.get());
        this.tag(MILD).add(ItemRegistry.Tofu.get());
        this.tag(MILD).add(ItemRegistry.Bamboo_Shoot.get());
        this.tag(MILD).add(ItemRegistry.Cucumber.get());
        this.tag(MILD).add(ItemRegistry.Dew.get());
        this.tag(MILD).add(ItemRegistry.Lotus_Seed.get());
        this.tag(MILD).add(ItemRegistry.Pine_Nut.get());
        this.tag(MILD).add(ItemRegistry.Snow_Fungus.get());
        this.tag(MILD).add(ItemRegistry.Lunar_Herb.get());
        this.tag(MILD).add(ItemRegistry.Bingdi_Lotus.get());
        this.tag(WESTERN).add(ItemRegistry.Cream.get());
        this.tag(GREASY).add(ItemRegistry.Butter.get());
        this.tag(FUNGUS).add(ItemRegistry.Mushroom.get());
        this.tag(FUNGUS).add(ItemRegistry.Truffle.get());
        this.tag(FUNGUS).add(ItemRegistry.Snow_Fungus.get());
        this.tag(AQUATIC).add(ItemRegistry.Crab.get());
        this.tag(AQUATIC).add(ItemRegistry.Sea_Urchin.get());
        this.tag(AQUATIC).add(ItemRegistry.Octopus.get());
        this.tag(AQUATIC).add(ItemRegistry.Shrimp.get());
        this.tag(AQUATIC).add(ItemRegistry.Pufferfish.get());
        this.tag(AQUATIC).add(ItemRegistry.Premium_Tuna.get());
        this.tag(AQUATIC).add(ItemRegistry.Tuna.get());
        this.tag(AQUATIC).add(ItemRegistry.Salmon.get());
        this.tag(AQUATIC).add(ItemRegistry.Lamprey.get());
        this.tag(AQUATIC).add(ItemRegistry.Trout.get());
        this.tag(SWEET).add(ItemRegistry.Cream.get());
        this.tag(SWEET).add(ItemRegistry.Cocoa_Bean.get());
        this.tag(SWEET).add(ItemRegistry.Peach.get());
        this.tag(SWEET).add(ItemRegistry.Honey.get());
        this.tag(FILLING).add(ItemRegistry.Pumpkin.get());
        this.tag(FILLING).add(ItemRegistry.Flour.get());
        this.tag(FILLING).add(ItemRegistry.Sweet_Potato.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Tofu.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Potato.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Cucumber.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Chestnut.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Broceoli.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Cream.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Red_Bean.get());
        this.tag(PHOTOGENIC).add(ItemRegistry.Ginko_Nut.get());
        this.tag(PHOTOGENIC).add(ItemRegistry.Bamboo.get());
        this.tag(PHOTOGENIC).add(ItemRegistry.Flower.get());
        this.tag(REFRESHING).add(ItemRegistry.Ice_Cube.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Tofu.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Potato.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Onion.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Pumpkin.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Radish.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Seaweed.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Mushroom.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Truffle.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Bamboo_Shoot.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Cucumber.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Chestnut.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Red_Toon.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Tomato.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Broceoli.get());
        this.tag(SMALL_PORTION).add(ItemRegistry.Plum.get());
        this.tag(SEA_DELICACY).add(ItemRegistry.Sea_Urchin.get());
        this.tag(SEA_DELICACY).add(ItemRegistry.Octopus.get());
        this.tag(SEA_DELICACY).add(ItemRegistry.Pufferfish.get());
        this.tag(SEA_DELICACY).add(ItemRegistry.Premium_Tuna.get());
        this.tag(PECULIAR).add(ItemRegistry.Cicada_Slough.get());
        this.tag(GOOD_ALCOHOL).add(ItemRegistry.Radish.get());
        this.tag(FRUITY).add(ItemRegistry.Grapes.get());
        this.tag(FRUITY).add(ItemRegistry.Lemon.get());
        this.tag(FRUITY).add(ItemRegistry.Peach.get());
        this.tag(SIGNATURE).add(ItemRegistry.Lamprey.get());
        this.tag(SIGNATURE).add(ItemRegistry.Lotus_Seed.get());
        this.tag(SIGNATURE).add(ItemRegistry.Pine_Nut.get());
        this.tag(WONDERFUL).add(ItemRegistry.Cocoa_Bean.get());
        this.tag(WONDERFUL).add(ItemRegistry.Udunmbara.get());
        this.tag(WONDERFUL).add(ItemRegistry.Lunar_Herb.get());
        this.tag(POISON).add(ItemRegistry.Red_Toon.get());
        this.tag(CULTURE_HERITAGE).add(ItemRegistry.Lotus_Seed.get());
        this.tag(CULTURE_HERITAGE).add(ItemRegistry.Lunar_Herb.get());
        this.tag(CULTURE_HERITAGE).add(ItemRegistry.Bingdi_Lotus.get());
        this.tag(SALTY).add(ItemRegistry.Black_Salt.get());
        this.tag(SALTY).add(ItemRegistry.Cheese.get());
        this.tag(SALTY).add(ItemRegistry.Plum.get());
        this.tag(SOUR).add(ItemRegistry.Lemon.get());
    }
}
