package com.crystal.mystia_izakaya.dataGen;

import com.crystal.mystia_izakaya.registry.ItemRegistry;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.ItemTagsProvider;
import net.minecraft.resources.ResourceKey;
import net.minecraft.tags.ItemTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import org.hiedacamellia.mystiasizakaya.registries.MIItem;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

import static com.crystal.mystia_izakaya.MystiaIzakaya.resourceLocation;

public class ModTagItem extends ItemTagsProvider {
    public static final TagKey<Item> FOOD_INGREDIENTS = TagKey.create(Registries.ITEM, resourceLocation("food_ingredients"));

    public static final TagKey<Item> SPECIALTY = TagKey.create(Registries.ITEM, resourceLocation("specialty"));
    public static final TagKey<Item> AURA_BURSTING = TagKey.create(Registries.ITEM, resourceLocation("aura_bursting"));
    public static final TagKey<Item> CULTURE_HERITAGE = TagKey.create(Registries.ITEM, resourceLocation("culture_heritage"));
    public static final TagKey<Item> STRENGTH_BOOSTING = TagKey.create(Registries.ITEM, resourceLocation("strength_boosting"));
    public static final TagKey<Item> JAPANESE = TagKey.create(Registries.ITEM, resourceLocation("japanese"));
    public static final TagKey<Item> CHINESE = TagKey.create(Registries.ITEM, resourceLocation("chinese"));
    public static final TagKey<Item> ECONOMICAL = TagKey.create(Registries.ITEM, resourceLocation("economical"));
    public static final TagKey<Item> MEAT = TagKey.create(Registries.ITEM, resourceLocation("meat"));
    public static final TagKey<Item> HOMECOOKING = TagKey.create(Registries.ITEM, resourceLocation("homecooking"));
    public static final TagKey<Item> SEA_DELICACY = TagKey.create(Registries.ITEM, resourceLocation("sea_delicacy"));
    public static final TagKey<Item> POISON = TagKey.create(Registries.ITEM, resourceLocation("poison"));
    public static final TagKey<Item> GRILLED = TagKey.create(Registries.ITEM, resourceLocation("grilled"));
    public static final TagKey<Item> DREAMY = TagKey.create(Registries.ITEM, resourceLocation("dreamy"));
    public static final TagKey<Item> SOUP = TagKey.create(Registries.ITEM, resourceLocation("soup"));
    public static final TagKey<Item> FRUITY = TagKey.create(Registries.ITEM, resourceLocation("fruity"));
    public static final TagKey<Item> PREMIUM = TagKey.create(Registries.ITEM, resourceLocation("premium"));
    public static final TagKey<Item> FRESH = TagKey.create(Registries.ITEM, resourceLocation("fresh"));
    public static final TagKey<Item> SWEET = TagKey.create(Registries.ITEM, resourceLocation("sweet"));
    public static final TagKey<Item> SIGNATURE = TagKey.create(Registries.ITEM, resourceLocation("signature"));
    public static final TagKey<Item> LEGENDARY = TagKey.create(Registries.ITEM, resourceLocation("legendary"));
    public static final TagKey<Item> GREASY = TagKey.create(Registries.ITEM, resourceLocation("greasy"));
    public static final TagKey<Item> REFRESHING = TagKey.create(Registries.ITEM, resourceLocation("refreshing"));
    public static final TagKey<Item> RAW = TagKey.create(Registries.ITEM, resourceLocation("raw"));
    public static final TagKey<Item> EMPTY = TagKey.create(Registries.ITEM, resourceLocation("empty"));
    public static final TagKey<Item> VEGETARIAN = TagKey.create(Registries.ITEM, resourceLocation("vegetarian"));
    public static final TagKey<Item> WESTERN = TagKey.create(Registries.ITEM, resourceLocation("western"));
    public static final TagKey<Item> SPICY = TagKey.create(Registries.ITEM, resourceLocation("spicy"));
    public static final TagKey<Item> GOOD_ALCOHOL = TagKey.create(Registries.ITEM, resourceLocation("good_alcohol"));
    public static final TagKey<Item> MILD = TagKey.create(Registries.ITEM, resourceLocation("mild"));
    public static final TagKey<Item> WONDERFUL = TagKey.create(Registries.ITEM, resourceLocation("wonderful"));
    public static final TagKey<Item> SMALL_PORTION = TagKey.create(Registries.ITEM, resourceLocation("small_portion"));
    public static final TagKey<Item> MOUNTAIN_DELICACY = TagKey.create(Registries.ITEM, resourceLocation("mountain_delicacy"));
    public static final TagKey<Item> PECULIAR = TagKey.create(Registries.ITEM, resourceLocation("peculiar"));
    public static final TagKey<Item> SALTY = TagKey.create(Registries.ITEM, resourceLocation("salty"));
    public static final TagKey<Item> SOUR = TagKey.create(Registries.ITEM, resourceLocation("sour"));
    public static final TagKey<Item> FILLING = TagKey.create(Registries.ITEM, resourceLocation("filling"));
    public static final TagKey<Item> LARGE_PORTION = TagKey.create(Registries.ITEM, resourceLocation("large_portion"));
    public static final TagKey<Item> AQUATIC = TagKey.create(Registries.ITEM, resourceLocation("aquatic"));
    public static final TagKey<Item> PHOTOGENIC = TagKey.create(Registries.ITEM, resourceLocation("photogenic"));
    public static final TagKey<Item> EXPENSIVE = TagKey.create(Registries.ITEM, resourceLocation("expensive"));
    public static final TagKey<Item> HOT = TagKey.create(Registries.ITEM, resourceLocation("hot"));
    public static final TagKey<Item> FUNGUS = TagKey.create(Registries.ITEM, resourceLocation("fungus"));

    public static final TagKey<Item> BEEF = TagKey.create(Registries.ITEM, resourceLocation("beef"));
    public static final TagKey<Item> FLOWER = TagKey.create(Registries.ITEM, resourceLocation("flower"));
    public static final TagKey<Item> CUTTING_BOARD = TagKey.create(Registries.ITEM, resourceLocation("cutting_board"));
    public static final TagKey<Item> CREAM = TagKey.create(Registries.ITEM, resourceLocation("cream"));
    public static final TagKey<Item> PUFFERFISH = TagKey.create(Registries.ITEM, resourceLocation("pufferfish"));
    public static final TagKey<Item> CUCUMBER = TagKey.create(Registries.ITEM, resourceLocation("cucumber"));
    public static final TagKey<Item> POTATO = TagKey.create(Registries.ITEM, resourceLocation("potato"));
    public static final TagKey<Item> BLACK_SALT = TagKey.create(Registries.ITEM, resourceLocation("black_salt"));
    public static final TagKey<Item> PORK = TagKey.create(Registries.ITEM, resourceLocation("pork"));
    public static final TagKey<Item> TUNA = TagKey.create(Registries.ITEM, resourceLocation("tuna"));
    public static final TagKey<Item> OCTOPUS = TagKey.create(Registries.ITEM, resourceLocation("octopus"));
    public static final TagKey<Item> LAMPREY = TagKey.create(Registries.ITEM, resourceLocation("lamprey"));
    public static final TagKey<Item> BINGDI_LOTUS = TagKey.create(Registries.ITEM, resourceLocation("bingdi_lotus"));
    public static final TagKey<Item> IBERICO_PORK = TagKey.create(Registries.ITEM, resourceLocation("iberico_pork"));
    public static final TagKey<Item> PINE_NUT = TagKey.create(Registries.ITEM, resourceLocation("pine_nut"));
    public static final TagKey<Item> SEA_URCHIN = TagKey.create(Registries.ITEM, resourceLocation("sea_urchin"));
    public static final TagKey<Item> COCOA_BEAN = TagKey.create(Registries.ITEM, resourceLocation("cocoa_bean"));
    public static final TagKey<Item> LUNAR_HERB = TagKey.create(Registries.ITEM, resourceLocation("lunar_herb"));
    public static final TagKey<Item> BROCEOLI = TagKey.create(Registries.ITEM, resourceLocation("broceoli"));
    public static final TagKey<Item> SWEET_POTATO = TagKey.create(Registries.ITEM, resourceLocation("sweet_potato"));
    public static final TagKey<Item> CREEPING_FIG = TagKey.create(Registries.ITEM, resourceLocation("creeping_fig"));
    public static final TagKey<Item> ICE_CUBE = TagKey.create(Registries.ITEM, resourceLocation("ice_cube"));
    public static final TagKey<Item> SALMON = TagKey.create(Registries.ITEM, resourceLocation("salmon"));
    public static final TagKey<Item> SEAWEED = TagKey.create(Registries.ITEM, resourceLocation("seaweed"));
    public static final TagKey<Item> GINKO_NUT = TagKey.create(Registries.ITEM, resourceLocation("ginko_nut"));
    public static final TagKey<Item> BAMBOO_SHOOT = TagKey.create(Registries.ITEM, resourceLocation("bamboo_shoot"));
    public static final TagKey<Item> LEMON = TagKey.create(Registries.ITEM, resourceLocation("lemon"));
    public static final TagKey<Item> WAGYO_BEEF = TagKey.create(Registries.ITEM, resourceLocation("wagyo_beef"));
    public static final TagKey<Item> CRAB = TagKey.create(Registries.ITEM, resourceLocation("crab"));
    public static final TagKey<Item> MUSHROOM = TagKey.create(Registries.ITEM, resourceLocation("mushroom"));
    public static final TagKey<Item> HONEY = TagKey.create(Registries.ITEM, resourceLocation("honey"));
    public static final TagKey<Item> ONION = TagKey.create(Registries.ITEM, resourceLocation("onion"));
    public static final TagKey<Item> GRILL = TagKey.create(Registries.ITEM, resourceLocation("grill"));
    public static final TagKey<Item> LOTUS_SEED = TagKey.create(Registries.ITEM, resourceLocation("lotus_seed"));
    public static final TagKey<Item> RADISH = TagKey.create(Registries.ITEM, resourceLocation("radish"));
    public static final TagKey<Item> TOMATO = TagKey.create(Registries.ITEM, resourceLocation("tomato"));
    public static final TagKey<Item> DEW = TagKey.create(Registries.ITEM, resourceLocation("dew"));
    public static final TagKey<Item> GRAPES = TagKey.create(Registries.ITEM, resourceLocation("grapes"));
    public static final TagKey<Item> RED_TOON = TagKey.create(Registries.ITEM, resourceLocation("red_toon"));
    public static final TagKey<Item> BOILING_POT = TagKey.create(Registries.ITEM, resourceLocation("boiling_pot"));
    public static final TagKey<Item> EGG = TagKey.create(Registries.ITEM, resourceLocation("egg"));
    public static final TagKey<Item> TOFU = TagKey.create(Registries.ITEM, resourceLocation("tofu"));
    public static final TagKey<Item> BOAR_MEAT = TagKey.create(Registries.ITEM, resourceLocation("boar_meat"));
    public static final TagKey<Item> STEAMER = TagKey.create(Registries.ITEM, resourceLocation("steamer"));
    public static final TagKey<Item> CHILI = TagKey.create(Registries.ITEM, resourceLocation("chili"));
    public static final TagKey<Item> FRYING_PAN = TagKey.create(Registries.ITEM, resourceLocation("frying_pan"));
    public static final TagKey<Item> PEACH = TagKey.create(Registries.ITEM, resourceLocation("peach"));
    public static final TagKey<Item> PREMIUM_TUNA = TagKey.create(Registries.ITEM, resourceLocation("premium_tuna"));
    public static final TagKey<Item> BUTTER = TagKey.create(Registries.ITEM, resourceLocation("butter"));
    public static final TagKey<Item> PLUM = TagKey.create(Registries.ITEM, resourceLocation("plum"));
    public static final TagKey<Item> STICKY_RICE = TagKey.create(Registries.ITEM, resourceLocation("sticky_rice"));
    public static final TagKey<Item> RED_BEAN = TagKey.create(Registries.ITEM, resourceLocation("red_bean"));
    public static final TagKey<Item> TROUT = TagKey.create(Registries.ITEM, resourceLocation("trout"));
    public static final TagKey<Item> PUMPKIN = TagKey.create(Registries.ITEM, resourceLocation("pumpkin"));
    public static final TagKey<Item> SNOW_FUNGUS = TagKey.create(Registries.ITEM, resourceLocation("snow_fungus"));
    public static final TagKey<Item> CHESTNUT = TagKey.create(Registries.ITEM, resourceLocation("chestnut"));
    public static final TagKey<Item> FLOUR = TagKey.create(Registries.ITEM, resourceLocation("flour"));
    public static final TagKey<Item> BAMBOO = TagKey.create(Registries.ITEM, resourceLocation("bamboo"));
    public static final TagKey<Item> VENISON = TagKey.create(Registries.ITEM, resourceLocation("venison"));
    public static final TagKey<Item> TRUFFLE = TagKey.create(Registries.ITEM, resourceLocation("truffle"));
    public static final TagKey<Item> CICADA_SLOUGH = TagKey.create(Registries.ITEM, resourceLocation("cicada_slough"));
    public static final TagKey<Item> SHRIMP = TagKey.create(Registries.ITEM, resourceLocation("shrimp"));
    public static final TagKey<Item> CHEESE = TagKey.create(Registries.ITEM, resourceLocation("cheese"));
    public static final TagKey<Item> UDUNMBARA = TagKey.create(Registries.ITEM, resourceLocation("udunmbara"));

    public ModTagItem(PackOutput pOutput, CompletableFuture<HolderLookup.Provider> pLookupProvider, CompletableFuture<TagLookup<Block>> pBlockTags, String modId, @Nullable ExistingFileHelper existingFileHelper) {
        super(pOutput, pLookupProvider, pBlockTags, modId, existingFileHelper);
    }

    private static <T> ResourceKey<Registry<T>> createRegistryKey(String name) {
        return ResourceKey.createRegistryKey(resourceLocation(name));
    }

    @Override
    protected void addTags(HolderLookup.@NotNull Provider pProvider) {
        this.tag(ItemTags.FISHING_ENCHANTABLE).add(ItemRegistry.MystiaFishingRod.value());
        LocalFoodIngredients();
        LocalFoodAttributeTags();
        LocalFoodTags();

        compat();
    }

    private void LocalFoodTags() {
        this.tag(BEEF).add(ItemRegistry.Beef.get());
        this.tag(FLOWER).add(ItemRegistry.Flower.get());
        this.tag(CUTTING_BOARD).add(ItemRegistry.Cutting_Board.get());
        this.tag(CREAM).add(ItemRegistry.Cream.get());
        this.tag(PUFFERFISH).add(ItemRegistry.Pufferfish.get());
        this.tag(CUCUMBER).add(ItemRegistry.Cucumber.get());
        this.tag(POTATO).add(ItemRegistry.Potato.get());
        this.tag(BLACK_SALT).add(ItemRegistry.Black_Salt.get());
        this.tag(PORK).add(ItemRegistry.Pork.get());
        this.tag(TUNA).add(ItemRegistry.Tuna.get());
        this.tag(OCTOPUS).add(ItemRegistry.Octopus.get());
        this.tag(LAMPREY).add(ItemRegistry.Lamprey.get());
        this.tag(BINGDI_LOTUS).add(ItemRegistry.Bingdi_Lotus.get());
        this.tag(IBERICO_PORK).add(ItemRegistry.Iberico_Pork.get());
        this.tag(PINE_NUT).add(ItemRegistry.Pine_Nut.get());
        this.tag(SEA_URCHIN).add(ItemRegistry.Sea_Urchin.get());
        this.tag(COCOA_BEAN).add(ItemRegistry.Cocoa_Bean.get());
        this.tag(LUNAR_HERB).add(ItemRegistry.Lunar_Herb.get());
        this.tag(BROCEOLI).add(ItemRegistry.Broceoli.get());
        this.tag(SWEET_POTATO).add(ItemRegistry.Sweet_Potato.get());
        this.tag(CREEPING_FIG).add(ItemRegistry.Creeping_Fig.get());
        this.tag(ICE_CUBE).add(ItemRegistry.Ice_Cube.get());
        this.tag(SALMON).add(ItemRegistry.Salmon.get());
        this.tag(SEAWEED).add(ItemRegistry.Seaweed.get());
        this.tag(GINKO_NUT).add(ItemRegistry.Ginko_Nut.get());
        this.tag(BAMBOO_SHOOT).add(ItemRegistry.Bamboo_Shoot.get());
        this.tag(LEMON).add(ItemRegistry.Lemon.get());
        this.tag(WAGYO_BEEF).add(ItemRegistry.Wagyo_Beef.get());
        this.tag(CRAB).add(ItemRegistry.Crab.get());
        this.tag(MUSHROOM).add(ItemRegistry.Mushroom.get());
        this.tag(HONEY).add(ItemRegistry.Honey.get());
        this.tag(ONION).add(ItemRegistry.Onion.get());
        this.tag(GRILL).add(ItemRegistry.Grill.get());
        this.tag(LOTUS_SEED).add(ItemRegistry.Lotus_Seed.get());
        this.tag(RADISH).add(ItemRegistry.Radish.get());
        this.tag(TOMATO).add(ItemRegistry.Tomato.get());
        this.tag(DEW).add(ItemRegistry.Dew.get());
        this.tag(GRAPES).add(ItemRegistry.Grapes.get());
        this.tag(RED_TOON).add(ItemRegistry.Red_Toon.get());
        this.tag(BOILING_POT).add(ItemRegistry.Boiling_Pot.get());
        this.tag(EGG).add(ItemRegistry.Egg.get());
        this.tag(TOFU).add(ItemRegistry.Tofu.get());
        this.tag(BOAR_MEAT).add(ItemRegistry.Boar_Meat.get());
        this.tag(STEAMER).add(ItemRegistry.Steamer.get());
        this.tag(CHILI).add(ItemRegistry.Chili.get());
        this.tag(FRYING_PAN).add(ItemRegistry.Frying_Pan.get());
        this.tag(PEACH).add(ItemRegistry.Peach.get());
        this.tag(PREMIUM_TUNA).add(ItemRegistry.Premium_Tuna.get());
        this.tag(BUTTER).add(ItemRegistry.Butter.get());
        this.tag(PLUM).add(ItemRegistry.Plum.get());
        this.tag(STICKY_RICE).add(ItemRegistry.Sticky_Rice.get());
        this.tag(RED_BEAN).add(ItemRegistry.Red_Bean.get());
        this.tag(TROUT).add(ItemRegistry.Trout.get());
        this.tag(PUMPKIN).add(ItemRegistry.Pumpkin.get());
        this.tag(SNOW_FUNGUS).add(ItemRegistry.Snow_Fungus.get());
        this.tag(CHESTNUT).add(ItemRegistry.Chestnut.get());
        this.tag(FLOUR).add(ItemRegistry.Flour.get());
        this.tag(BAMBOO).add(ItemRegistry.Bamboo.get());
        this.tag(VENISON).add(ItemRegistry.Venison.get());
        this.tag(TRUFFLE).add(ItemRegistry.Truffle.get());
        this.tag(CICADA_SLOUGH).add(ItemRegistry.Cicada_Slough.get());
        this.tag(SHRIMP).add(ItemRegistry.Shrimp.get());
        this.tag(CHEESE).add(ItemRegistry.Cheese.get());
        this.tag(UDUNMBARA).add(ItemRegistry.Udunmbara.get());
    }

    private void LocalFoodAttributeTags() {
        this.tag(FRESH).add(ItemRegistry.Crab.get());
        this.tag(FRESH).add(ItemRegistry.Sea_Urchin.get());
        this.tag(FRESH).add(ItemRegistry.Octopus.get());
        this.tag(FRESH).add(ItemRegistry.Shrimp.get());
        this.tag(FRESH).add(ItemRegistry.Pufferfish.get());
        this.tag(FRESH).add(ItemRegistry.Premium_Tuna.get());
        this.tag(FRESH).add(ItemRegistry.Tuna.get());
        this.tag(FRESH).add(ItemRegistry.Salmon.get());
        this.tag(FRESH).add(ItemRegistry.Lamprey.get());
        this.tag(FRESH).add(ItemRegistry.Trout.get());
        this.tag(FRESH).add(ItemRegistry.Onion.get());
        this.tag(FRESH).add(ItemRegistry.Seaweed.get());
        this.tag(FRESH).add(ItemRegistry.Mushroom.get());
        this.tag(FRESH).add(ItemRegistry.Truffle.get());
        this.tag(FRESH).add(ItemRegistry.Cheese.get());
        this.tag(LEGENDARY).add(ItemRegistry.Sea_Urchin.get());
        this.tag(LEGENDARY).add(ItemRegistry.Premium_Tuna.get());
        this.tag(LEGENDARY).add(ItemRegistry.Iberico_Pork.get());
        this.tag(LEGENDARY).add(ItemRegistry.Wagyo_Beef.get());
        this.tag(LEGENDARY).add(ItemRegistry.Truffle.get());
        this.tag(LEGENDARY).add(ItemRegistry.Udunmbara.get());
        this.tag(LEGENDARY).add(ItemRegistry.Bingdi_Lotus.get());
        this.tag(SPICY).add(ItemRegistry.Chili.get());
        this.tag(MOUNTAIN_DELICACY).add(ItemRegistry.Iberico_Pork.get());
        this.tag(MOUNTAIN_DELICACY).add(ItemRegistry.Truffle.get());
        this.tag(RAW).add(ItemRegistry.Egg.get());
        this.tag(DREAMY).add(ItemRegistry.Udunmbara.get());
        this.tag(DREAMY).add(ItemRegistry.Lunar_Herb.get());
        this.tag(DREAMY).add(ItemRegistry.Bingdi_Lotus.get());
        this.tag(DREAMY).add(ItemRegistry.Flower.get());
        this.tag(PREMIUM).add(ItemRegistry.Crab.get());
        this.tag(PREMIUM).add(ItemRegistry.Sea_Urchin.get());
        this.tag(PREMIUM).add(ItemRegistry.Premium_Tuna.get());
        this.tag(PREMIUM).add(ItemRegistry.Tuna.get());
        this.tag(PREMIUM).add(ItemRegistry.Salmon.get());
        this.tag(PREMIUM).add(ItemRegistry.Wagyo_Beef.get());
        this.tag(PREMIUM).add(ItemRegistry.Truffle.get());
        this.tag(PREMIUM).add(ItemRegistry.Pine_Nut.get());
        this.tag(PREMIUM).add(ItemRegistry.Udunmbara.get());
        this.tag(PREMIUM).add(ItemRegistry.Bingdi_Lotus.get());
        this.tag(PREMIUM).add(ItemRegistry.Cheese.get());
        this.tag(MEAT).add(ItemRegistry.Pork.get());
        this.tag(MEAT).add(ItemRegistry.Beef.get());
        this.tag(MEAT).add(ItemRegistry.Venison.get());
        this.tag(MEAT).add(ItemRegistry.Boar_Meat.get());
        this.tag(MEAT).add(ItemRegistry.Iberico_Pork.get());
        this.tag(MEAT).add(ItemRegistry.Wagyo_Beef.get());
        this.tag(MILD).add(ItemRegistry.Tofu.get());
        this.tag(MILD).add(ItemRegistry.Bamboo_Shoot.get());
        this.tag(MILD).add(ItemRegistry.Cucumber.get());
        this.tag(MILD).add(ItemRegistry.Dew.get());
        this.tag(MILD).add(ItemRegistry.Lotus_Seed.get());
        this.tag(MILD).add(ItemRegistry.Pine_Nut.get());
        this.tag(MILD).add(ItemRegistry.Snow_Fungus.get());
        this.tag(MILD).add(ItemRegistry.Lunar_Herb.get());
        this.tag(MILD).add(ItemRegistry.Bingdi_Lotus.get());
        this.tag(WESTERN).add(ItemRegistry.Cream.get());
        this.tag(GREASY).add(ItemRegistry.Butter.get());
        this.tag(FUNGUS).add(ItemRegistry.Mushroom.get());
        this.tag(FUNGUS).add(ItemRegistry.Truffle.get());
        this.tag(FUNGUS).add(ItemRegistry.Snow_Fungus.get());
        this.tag(AQUATIC).add(ItemRegistry.Crab.get());
        this.tag(AQUATIC).add(ItemRegistry.Sea_Urchin.get());
        this.tag(AQUATIC).add(ItemRegistry.Octopus.get());
        this.tag(AQUATIC).add(ItemRegistry.Shrimp.get());
        this.tag(AQUATIC).add(ItemRegistry.Pufferfish.get());
        this.tag(AQUATIC).add(ItemRegistry.Premium_Tuna.get());
        this.tag(AQUATIC).add(ItemRegistry.Tuna.get());
        this.tag(AQUATIC).add(ItemRegistry.Salmon.get());
        this.tag(AQUATIC).add(ItemRegistry.Lamprey.get());
        this.tag(AQUATIC).add(ItemRegistry.Trout.get());
        this.tag(SWEET).add(ItemRegistry.Cream.get());
        this.tag(SWEET).add(ItemRegistry.Cocoa_Bean.get());
        this.tag(SWEET).add(ItemRegistry.Peach.get());
        this.tag(SWEET).add(ItemRegistry.Honey.get());
        this.tag(FILLING).add(ItemRegistry.Pumpkin.get());
        this.tag(FILLING).add(ItemRegistry.Flour.get());
        this.tag(FILLING).add(ItemRegistry.Sweet_Potato.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Tofu.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Potato.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Cucumber.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Chestnut.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Broceoli.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Cream.get());
        this.tag(HOMECOOKING).add(ItemRegistry.Red_Bean.get());
        this.tag(PHOTOGENIC).add(ItemRegistry.Ginko_Nut.get());
        this.tag(PHOTOGENIC).add(ItemRegistry.Bamboo.get());
        this.tag(PHOTOGENIC).add(ItemRegistry.Flower.get());
        this.tag(REFRESHING).add(ItemRegistry.Ice_Cube.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Tofu.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Potato.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Onion.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Pumpkin.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Radish.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Seaweed.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Mushroom.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Truffle.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Bamboo_Shoot.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Cucumber.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Chestnut.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Red_Toon.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Tomato.get());
        this.tag(VEGETARIAN).add(ItemRegistry.Broceoli.get());
        this.tag(SMALL_PORTION).add(ItemRegistry.Plum.get());
        this.tag(SEA_DELICACY).add(ItemRegistry.Sea_Urchin.get());
        this.tag(SEA_DELICACY).add(ItemRegistry.Octopus.get());
        this.tag(SEA_DELICACY).add(ItemRegistry.Pufferfish.get());
        this.tag(SEA_DELICACY).add(ItemRegistry.Premium_Tuna.get());
        this.tag(PECULIAR).add(ItemRegistry.Cicada_Slough.get());
        this.tag(GOOD_ALCOHOL).add(ItemRegistry.Radish.get());
        this.tag(FRUITY).add(ItemRegistry.Grapes.get());
        this.tag(FRUITY).add(ItemRegistry.Lemon.get());
        this.tag(FRUITY).add(ItemRegistry.Peach.get());
        this.tag(SIGNATURE).add(ItemRegistry.Lamprey.get());
        this.tag(SIGNATURE).add(ItemRegistry.Lotus_Seed.get());
        this.tag(SIGNATURE).add(ItemRegistry.Pine_Nut.get());
        this.tag(WONDERFUL).add(ItemRegistry.Cocoa_Bean.get());
        this.tag(WONDERFUL).add(ItemRegistry.Udunmbara.get());
        this.tag(WONDERFUL).add(ItemRegistry.Lunar_Herb.get());
        this.tag(POISON).add(ItemRegistry.Red_Toon.get());
        this.tag(CULTURE_HERITAGE).add(ItemRegistry.Lotus_Seed.get());
        this.tag(CULTURE_HERITAGE).add(ItemRegistry.Lunar_Herb.get());
        this.tag(CULTURE_HERITAGE).add(ItemRegistry.Bingdi_Lotus.get());
        this.tag(SALTY).add(ItemRegistry.Black_Salt.get());
        this.tag(SALTY).add(ItemRegistry.Cheese.get());
        this.tag(SALTY).add(ItemRegistry.Plum.get());
        this.tag(SOUR).add(ItemRegistry.Lemon.get());
    }

    private void LocalFoodIngredients() {
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Crab.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Grill.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Trout.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Lamprey.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Salmon.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Tuna.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Premium_Tuna.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Pufferfish.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Shrimp.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Octopus.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Sea_Urchin.get());

        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Pork.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Beef.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Venison.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Boar_Meat.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Iberico_Pork.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Wagyo_Beef.get());

        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Tofu.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Potato.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Onion.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Pumpkin.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Radish.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Seaweed.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Mushroom.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Truffle.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Bamboo_Shoot.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Cucumber.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Chestnut.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Red_Toon.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Tomato.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Broceoli.get());

        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Egg.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Ginko_Nut.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Cicada_Slough.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Dew.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Flour.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Sticky_Rice.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Ice_Cube.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Grapes.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Cream.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Lemon.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Lotus_Seed.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Pine_Nut.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Red_Bean.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Cocoa_Bean.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Snow_Fungus.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Peach.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Honey.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Udunmbara.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Butter.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Bamboo.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Lunar_Herb.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Chili.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Black_Salt.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Bingdi_Lotus.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Cheese.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Sweet_Potato.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Plum.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Flower.get());
        this.tag(FOOD_INGREDIENTS).add(ItemRegistry.Creeping_Fig.get());
    }

    private void compat() {
        this.tag(FOOD_INGREDIENTS).add(MIItem.PANG_XIE.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.HAI_DAN.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.ZHANG_YU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.XIA.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.HE_TUN.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.JI_SHANG_JIN_QIANG_YU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.JIN_QIANG_YU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.SAN_WEN_YU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.BA_MU_MAN.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.ZUN_YU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.ZHU_ROU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.NIU_ROU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.LU_ROU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.YE_ZHU_ROU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.HEI_MAO_ZHU_ROU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.HE_NIU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.DOU_FU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.TU_DOU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.YANG_CONG.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.NAN_GUA.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.LUO_BU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.HAI_TAI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.MO_GU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.SONG_LU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.ZHU_SUN.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.HUANG_GUA.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.BAN_LI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.CHUN_CHUN.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.XI_HONG_SHI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.XI_LAN_HUA.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.JI_DAN.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.BAI_GUO.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.CHAN_SHUI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.LU_SHUI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.MIAN_FEN.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.NUO_MI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.BING_KUAI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.PU_TAO.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.NAI_YOU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.NING_MENG.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.LIAN_ZI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.SONG_ZI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.HONG_DOU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.KE_KE_DOU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.YIN_ER.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.TAO_ZI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.FENG_MI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.HUAN_TAN_HUA.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.HUANG_YOU.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.ZHU_ZI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.YUE_GUANG_CAO.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.LA_JIAO.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.HEI_YAN.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.BING_DI_LIAN.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.ZHI_SHI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.DI_GUA.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.MEI_ZI.get());
        this.tag(FOOD_INGREDIENTS).add(MIItem.XIAN_HUA.get());

        this.tag(FRESH).add(MIItem.PANG_XIE.get());
        this.tag(FRESH).add(MIItem.HAI_DAN.get());
        this.tag(FRESH).add(MIItem.ZHANG_YU.get());
        this.tag(FRESH).add(MIItem.XIA.get());
        this.tag(FRESH).add(MIItem.HE_TUN.get());
        this.tag(FRESH).add(MIItem.JI_SHANG_JIN_QIANG_YU.get());
        this.tag(FRESH).add(MIItem.JIN_QIANG_YU.get());
        this.tag(FRESH).add(MIItem.SAN_WEN_YU.get());
        this.tag(FRESH).add(MIItem.BA_MU_MAN.get());
        this.tag(FRESH).add(MIItem.ZUN_YU.get());
        this.tag(FRESH).add(MIItem.YANG_CONG.get());
        this.tag(FRESH).add(MIItem.HAI_TAI.get());
        this.tag(FRESH).add(MIItem.MO_GU.get());
        this.tag(FRESH).add(MIItem.SONG_LU.get());
        this.tag(FRESH).add(MIItem.ZHI_SHI.get());
        this.tag(LEGENDARY).add(MIItem.HAI_DAN.get());
        this.tag(LEGENDARY).add(MIItem.JI_SHANG_JIN_QIANG_YU.get());
        this.tag(LEGENDARY).add(MIItem.HEI_MAO_ZHU_ROU.get());
        this.tag(LEGENDARY).add(MIItem.HE_NIU.get());
        this.tag(LEGENDARY).add(MIItem.SONG_LU.get());
        this.tag(LEGENDARY).add(MIItem.HUAN_TAN_HUA.get());
        this.tag(LEGENDARY).add(MIItem.BING_DI_LIAN.get());
        this.tag(SPICY).add(MIItem.LA_JIAO.get());
        this.tag(MOUNTAIN_DELICACY).add(MIItem.HEI_MAO_ZHU_ROU.get());
        this.tag(MOUNTAIN_DELICACY).add(MIItem.SONG_LU.get());
        this.tag(RAW).add(MIItem.JI_DAN.get());
        this.tag(DREAMY).add(MIItem.HUAN_TAN_HUA.get());
        this.tag(DREAMY).add(MIItem.YUE_GUANG_CAO.get());
        this.tag(DREAMY).add(MIItem.BING_DI_LIAN.get());
        this.tag(DREAMY).add(MIItem.XIAN_HUA.get());
        this.tag(PREMIUM).add(MIItem.PANG_XIE.get());
        this.tag(PREMIUM).add(MIItem.HAI_DAN.get());
        this.tag(PREMIUM).add(MIItem.JI_SHANG_JIN_QIANG_YU.get());
        this.tag(PREMIUM).add(MIItem.JIN_QIANG_YU.get());
        this.tag(PREMIUM).add(MIItem.SAN_WEN_YU.get());
        this.tag(PREMIUM).add(MIItem.HE_NIU.get());
        this.tag(PREMIUM).add(MIItem.SONG_LU.get());
        this.tag(PREMIUM).add(MIItem.SONG_ZI.get());
        this.tag(PREMIUM).add(MIItem.HUAN_TAN_HUA.get());
        this.tag(PREMIUM).add(MIItem.BING_DI_LIAN.get());
        this.tag(PREMIUM).add(MIItem.ZHI_SHI.get());
        this.tag(MEAT).add(MIItem.ZHU_ROU.get());
        this.tag(MEAT).add(MIItem.NIU_ROU.get());
        this.tag(MEAT).add(MIItem.LU_ROU.get());
        this.tag(MEAT).add(MIItem.YE_ZHU_ROU.get());
        this.tag(MEAT).add(MIItem.HEI_MAO_ZHU_ROU.get());
        this.tag(MEAT).add(MIItem.HE_NIU.get());
        this.tag(MILD).add(MIItem.DOU_FU.get());
        this.tag(MILD).add(MIItem.ZHU_SUN.get());
        this.tag(MILD).add(MIItem.HUANG_GUA.get());
        this.tag(MILD).add(MIItem.LU_SHUI.get());
        this.tag(MILD).add(MIItem.LIAN_ZI.get());
        this.tag(MILD).add(MIItem.SONG_ZI.get());
        this.tag(MILD).add(MIItem.YIN_ER.get());
        this.tag(MILD).add(MIItem.YUE_GUANG_CAO.get());
        this.tag(MILD).add(MIItem.BING_DI_LIAN.get());
        this.tag(WESTERN).add(MIItem.NAI_YOU.get());
        this.tag(GREASY).add(MIItem.HUANG_YOU.get());
        this.tag(FUNGUS).add(MIItem.MO_GU.get());
        this.tag(FUNGUS).add(MIItem.SONG_LU.get());
        this.tag(FUNGUS).add(MIItem.YIN_ER.get());
        this.tag(AQUATIC).add(MIItem.PANG_XIE.get());
        this.tag(AQUATIC).add(MIItem.HAI_DAN.get());
        this.tag(AQUATIC).add(MIItem.ZHANG_YU.get());
        this.tag(AQUATIC).add(MIItem.XIA.get());
        this.tag(AQUATIC).add(MIItem.HE_TUN.get());
        this.tag(AQUATIC).add(MIItem.JI_SHANG_JIN_QIANG_YU.get());
        this.tag(AQUATIC).add(MIItem.JIN_QIANG_YU.get());
        this.tag(AQUATIC).add(MIItem.SAN_WEN_YU.get());
        this.tag(AQUATIC).add(MIItem.BA_MU_MAN.get());
        this.tag(AQUATIC).add(MIItem.ZUN_YU.get());
        this.tag(SWEET).add(MIItem.NAI_YOU.get());
        this.tag(SWEET).add(MIItem.KE_KE_DOU.get());
        this.tag(SWEET).add(MIItem.TAO_ZI.get());
        this.tag(SWEET).add(MIItem.FENG_MI.get());
        this.tag(FILLING).add(MIItem.NAN_GUA.get());
        this.tag(FILLING).add(MIItem.MIAN_FEN.get());
        this.tag(FILLING).add(MIItem.DI_GUA.get());
        this.tag(HOMECOOKING).add(MIItem.DOU_FU.get());
        this.tag(HOMECOOKING).add(MIItem.TU_DOU.get());
        this.tag(HOMECOOKING).add(MIItem.HUANG_GUA.get());
        this.tag(HOMECOOKING).add(MIItem.BAN_LI.get());
        this.tag(HOMECOOKING).add(MIItem.XI_LAN_HUA.get());
        this.tag(HOMECOOKING).add(MIItem.NAI_YOU.get());
        this.tag(HOMECOOKING).add(MIItem.HONG_DOU.get());
        this.tag(PHOTOGENIC).add(MIItem.BAI_GUO.get());
        this.tag(PHOTOGENIC).add(MIItem.ZHU_ZI.get());
        this.tag(PHOTOGENIC).add(MIItem.XIAN_HUA.get());
        this.tag(REFRESHING).add(MIItem.BING_KUAI.get());
        this.tag(VEGETARIAN).add(MIItem.DOU_FU.get());
        this.tag(VEGETARIAN).add(MIItem.TU_DOU.get());
        this.tag(VEGETARIAN).add(MIItem.YANG_CONG.get());
        this.tag(VEGETARIAN).add(MIItem.NAN_GUA.get());
        this.tag(VEGETARIAN).add(MIItem.LUO_BU.get());
        this.tag(VEGETARIAN).add(MIItem.HAI_TAI.get());
        this.tag(VEGETARIAN).add(MIItem.MO_GU.get());
        this.tag(VEGETARIAN).add(MIItem.SONG_LU.get());
        this.tag(VEGETARIAN).add(MIItem.ZHU_SUN.get());
        this.tag(VEGETARIAN).add(MIItem.HUANG_GUA.get());
        this.tag(VEGETARIAN).add(MIItem.BAN_LI.get());
        this.tag(VEGETARIAN).add(MIItem.CHUN_CHUN.get());
        this.tag(VEGETARIAN).add(MIItem.XI_HONG_SHI.get());
        this.tag(VEGETARIAN).add(MIItem.XI_LAN_HUA.get());
        this.tag(SMALL_PORTION).add(MIItem.MEI_ZI.get());
        this.tag(SEA_DELICACY).add(MIItem.HAI_DAN.get());
        this.tag(SEA_DELICACY).add(MIItem.ZHANG_YU.get());
        this.tag(SEA_DELICACY).add(MIItem.HE_TUN.get());
        this.tag(SEA_DELICACY).add(MIItem.JI_SHANG_JIN_QIANG_YU.get());
        this.tag(PECULIAR).add(MIItem.CHAN_SHUI.get());
        this.tag(GOOD_ALCOHOL).add(MIItem.LUO_BU.get());
        this.tag(FRUITY).add(MIItem.PU_TAO.get());
        this.tag(FRUITY).add(MIItem.NING_MENG.get());
        this.tag(FRUITY).add(MIItem.TAO_ZI.get());
        this.tag(SIGNATURE).add(MIItem.BA_MU_MAN.get());
        this.tag(SIGNATURE).add(MIItem.LIAN_ZI.get());
        this.tag(SIGNATURE).add(MIItem.SONG_ZI.get());
        this.tag(WONDERFUL).add(MIItem.KE_KE_DOU.get());
        this.tag(WONDERFUL).add(MIItem.HUAN_TAN_HUA.get());
        this.tag(WONDERFUL).add(MIItem.YUE_GUANG_CAO.get());
        this.tag(POISON).add(MIItem.CHUN_CHUN.get());
        this.tag(CULTURE_HERITAGE).add(MIItem.LIAN_ZI.get());
        this.tag(CULTURE_HERITAGE).add(MIItem.YUE_GUANG_CAO.get());
        this.tag(CULTURE_HERITAGE).add(MIItem.BING_DI_LIAN.get());
        this.tag(SALTY).add(MIItem.HEI_YAN.get());
        this.tag(SALTY).add(MIItem.ZHI_SHI.get());
        this.tag(SALTY).add(MIItem.MEI_ZI.get());
        this.tag(SOUR).add(MIItem.NING_MENG.get());
    }
}
