@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.crystal.mystia_izakaya.compat.touhou_little_maid;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;