modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

issueTrackerURL="https://github.com/Crystal1921/mystias_izakaya/issues" #optional

[[mods]] #mandatory

enumExtensions="META-INF/enumextensions.json"

modId="${mod_id}" #mandatory

version="${mod_version}" #mandatory

displayName="${mod_name}" #mandatory

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

logoFile="logo.png" #optional

credits="Dichroic Purpilion - Re零同人社, ZUN" #optional

authors="${mod_authors}" #optional

description='''${mod_description}'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
#[[mixins]]
#config="${mod_id}.mixins.json"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

[[dependencies.${ mod_id }]]
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="${neo_version_range}" #mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT, or SERVER
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${ mod_id }]]
modId = "touhou_little_maid"
mandatory = true
versionRange = "${touhou_little_maid_version_range}"
ordering = "NONE"
side = "BOTH"
