@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.crystal.mystia_izakaya.client.block;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;